services:
  ros2_builder:
    profiles:
      - teleop
      - teleop-leader
      - teleop-follower
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
    command: /workspace/scripts/docker/build-entrypoint.sh

  crane_x7_ros2_real:
    profiles:
      - real
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    devices:
      - "$USB_DEVICE:/dev/ttyUSB0"
    group_add:
      - dialout
      - "985"  # uucp group GID on Arch Linux
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log real_with_logger.launch.py

  crane_x7_ros2_sim:
    profiles:
      - sim
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log demo_with_logger.launch.py

  crane_x7_teleop_leader:
    profiles:
      - teleop-leader
      - teleop
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    devices:
      - "$USB_DEVICE:/dev/ttyUSB0"
    group_add:
      - dialout
      - "985"  # uucp group GID on Arch Linux
    depends_on:
      - ros2_builder
    command: /workspace/scripts/docker/run-entrypoint.sh ros2 launch crane_x7_teleop teleop_leader.launch.py

  crane_x7_teleop_follower:
    profiles:
      - teleop-follower
      - teleop
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    devices:
      - "${USB_DEVICE_FOLLOWER:-/dev/ttyUSB1}:/dev/ttyUSB0"
    group_add:
      - dialout
      - "985"  # uucp group GID on Arch Linux
    depends_on:
      - ros2_builder
    command: /workspace/scripts/docker/run-entrypoint.sh ros2 launch crane_x7_teleop teleop_with_logger.launch.py

  vla_finetune:
    profiles:
      - vla
    build:
      context: .
      dockerfile: Dockerfile
      target: vla
    volumes:
      - type: bind
        source: "./vla"
        target: "/workspace/vla"
      - type: bind
        source: "./data"
        target: "/workspace/data"
      - type: bind
        source: "./outputs"
        target: "/workspace/outputs"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16gb'
    ipc: host
    working_dir: /workspace
    command: /bin/bash

networks:
  default:
    name: crane_x7

