services:
  crane_x7_ros2_real:
    profiles:
      - real
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    devices:
      - "$USB_DEVICE:/dev/ttyUSB0"
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log real_with_logger.launch.py

  crane_x7_ros2_sim:
    profiles:
      - sim
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log demo_with_logger.launch.py

  vla_finetune:
    profiles:
      - vla
    build:
      context: .
      dockerfile: Dockerfile
      target: vla
    volumes:
      - type: bind
        source: "./vla"
        target: "/workspace/vla"
      - type: bind
        source: "./data"
        target: "/workspace/data"
      - type: bind
        source: "./outputs"
        target: "/workspace/outputs"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16gb'
    ipc: host
    working_dir: /workspace
    command: /bin/bash

networks:
  default:
    name: crane_x7

