services:
  crane_x7_ros2_real:
    profiles:
      - real
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    devices:
      - "$USB_DEVICE:/dev/ttyUSB0"
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log real_with_logger.launch.py

  crane_x7_ros2_sim:
    profiles:
      - sim
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - type: bind
        source: "."
        target: "/workspace"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    command: /workspace/scripts/docker/entrypoint.sh ros2 launch crane_x7_log demo_with_logger.launch.py

networks:
  default:
    name: crane_x7

